// Command api is the Canopy HTTP API entrypoint.
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/canopy/api/internal/admin"
	"github.com/canopy/api/internal/ai"
	"github.com/canopy/api/internal/auth"
	"github.com/canopy/api/internal/care"
	"github.com/canopy/api/internal/config"
	"github.com/canopy/api/internal/content"
	"github.com/canopy/api/internal/crypto"
	"github.com/canopy/api/internal/httpx"
	"github.com/canopy/api/internal/kyc"
	"github.com/canopy/api/internal/mailer"
	"github.com/canopy/api/internal/platform/logging"
	"github.com/canopy/api/internal/platform/postgres"
	"github.com/canopy/api/internal/storage"
	"github.com/canopy/api/internal/sysconfig"
	"github.com/canopy/api/internal/system"
)

func main() {
	if err := run(); err != nil {
		slog.Error("fatal", "err", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	logger := logging.New(cfg.LogLevel, cfg.LogFormat)
	slog.SetDefault(logger)
	logger.Info("starting canopy api", "env", cfg.AppEnv, "port", cfg.AppPort, "version", config.Version)

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Postgres (non-fatal at boot; readiness reports it instead of crash-looping).
	db, err := postgres.Connect(ctx, cfg.DatabaseURL, cfg.DBMaxConns, cfg.DBMinConns)
	if err != nil {
		logger.Warn("postgres not reachable at boot; continuing", "err", err)
	}
	if db != nil {
		defer db.Close()
	}

	// Secrets-at-rest cipher.
	cipher, err := crypto.New(cfg.ConfigEncryptionKey)
	if err != nil {
		return err
	}

	// Object storage (no network call here).
	storageClient, err := storage.New(storage.Config{
		Endpoint:  cfg.MinIOEndpoint,
		AccessKey: cfg.MinIOAccessKey,
		SecretKey: cfg.MinIOSecretKey,
		Bucket:    cfg.MinIOBucket,
		UseSSL:    cfg.MinIOUseSSL,
		PublicURL: cfg.MinIOPublicURL,
	})
	if err != nil {
		return err
	}

	// Config service (encrypted DB-backed config + AI providers).
	cfgSvc := sysconfig.NewService(sysconfig.NewRepo(db), cipher, 30*time.Second)
	if db != nil {
		if err := cfgSvc.Reload(ctx); err != nil {
			logger.Warn("initial config load failed", "err", err)
		}
	}

	// Readiness (real checks).
	readiness := system.NewReadiness(db, cfgSvc, storageClient)

	// Auth (with transactional email via Resend, configured at runtime).
	tm := auth.NewTokenManager(jwtSecret(cfg.JWTAccessSecret, logger), cfg.JWTAccessTTL, cfg.JWTRefreshTTL)
	authSvc := auth.NewService(auth.NewRepo(db), tm, mailer.New(cfgSvc), cfg.AppBaseURL)
	authMW := auth.NewMiddleware(tm)
	authHandler := auth.NewHandler(authSvc, authMW)

	if db != nil {
		if err := authSvc.Bootstrap(ctx, cfg.BootstrapAdminEmail, cfg.BootstrapAdminPassword); err != nil {
			logger.Warn("admin bootstrap failed", "err", err)
		}
	}

	// Admin config surface.
	adminHandler := admin.NewHandler(cfgSvc, storageClient, admin.NewTester(), auth.NewRepo(db))

	// AI (identify / diagnose / chat) via the configured provider.
	aiSvc := ai.NewService(cfgSvc)
	aiHandler := ai.NewHandler(aiSvc)

	// Care plans (phác đồ chăm sóc) — persisted roadmaps generated by the AI.
	careHandler := care.NewHandler(care.NewRepo(db), aiSvc)

	// KYC — identity verification + seller/caretaker role applications.
	kycHandler := kyc.NewHandler(kyc.NewRepo(db), storageClient)

	srv := httpx.NewServer(httpx.Deps{
		Config:       cfg,
		Logger:       logger,
		DB:           db,
		Readiness:    readiness,
		AuthHandler:  authHandler,
		AuthMW:       authMW,
		AdminHandler: adminHandler,
		AIHandler:    aiHandler,
		CareHandler:  careHandler,
		KYCHandler:   kycHandler,
		Sysconfig:    cfgSvc,
		Content:      content.NewService(),
	})

	httpServer := &http.Server{
		Addr:              ":" + cfg.AppPort,
		Handler:           srv.Handler(),
		ReadHeaderTimeout: 10 * time.Second,
	}

	go func() {
		logger.Info("http listening", "addr", httpServer.Addr)
		if err := httpServer.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Error("http server error", "err", err)
			stop()
		}
	}()

	<-ctx.Done()
	logger.Info("shutdown signal received, draining connections")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err := httpServer.Shutdown(shutdownCtx); err != nil {
		return err
	}
	logger.Info("bye")
	return nil
}

// jwtSecret falls back to a dev secret when unset, so local runs work; a real
// secret is mandatory in production deployments.
func jwtSecret(s string, logger *slog.Logger) string {
	if s == "" {
		logger.Warn("JWT secret not set; using insecure dev secret")
		return "canopy-dev-insecure-jwt-secret"
	}
	return s
}
